language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
services:
    - docker
script:
    - cd client-app &&
      npm i &&
      npm run build &&
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker build . -t $IMAGE_NAME;
        docker tag $IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPOSITORY;
        docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY;
        fi
#TODO: concatenating strings as in --parameters above introduces vulnerability of possible command injection, it needs to change
