#language: node_js
#node_js:
#  - "stable"
#cache:
#  directories:
#    - node_modules
#services:
#  - docker
#
#variables:
##  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
##  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
##  INSTANCE_ID: $INSTANCE_ID
#  DOCKER_SWARM_UPDATE_COMMAND: "docker service update unstableStackk_client-app --image alagiz/instability_client-app"
script:
    AWS_COMMAND="docker service update --image $DOCKER_USERNAME/$DOCKER_REPOSITORY $DOCKER_SWARM_SERVICE_NAME";
    AWS_COMMAND_PARAMETERS='{"commands":["$AWS_COMMAND"],"executionTimeout":["3600"]}';
    echo AWS_COMMAND_PARAMETERS;
